name: Cypress Tests 

on:
  push:
   branches:
   - main

jobs:
cypress-tests-GoIT5:
runs-on: ubuntu-latest

steps:
- name: Chechout Repository GoIT5
uses: actions/chekout@v4

-name: Install Dependencies GoIT5
run: npm install

-name: Run Cypress Tests GoIT5
run: npm run moj:super:skrypt:GoIT5